[workspace]
authors = ["Thomas A Caswell <tcaswell@bnl.gov>"]
channels = ["conda-forge"]
name = "Lab6_testdata_share"
platforms = ["linux-64", "win-64", "osx-64"]
version = "0.1.0"

[tasks]

[environments]
pre-commit = { features = ["pre-commit"], solve-group = "pre-commit", no-default-feature = true }

[dependencies]
matplotlib = ">=3.10.1,<4"
ipython = ">=9.2.0,<10"
numpy = ">=2.2.5,<3"
h5py = ">=3.13.0,<4"
hdf5-external-filter-plugins-lz4 = ">=0.1.0,<0.2"
hdf5-external-filter-plugins-bitshuffle = ">=0.1.0,<0.2"
scikit-image = ">=0.25.2,<0.26"
xarray = ">=2025.4.0,<2026"
tqdm = ">=4.67.1,<5"
python = ">=3.13"
pyyaml = ">=6.0.2,<7"
pytest = ">=8.3.5,<9"
hdf5plugin = ">=6.0.0,<7"

[feature.pre-commit.dependencies]
pre-commit = ">=4.0.0,<5"

[feature.pre-commit.tasks]
pre-commit = "pre-commit run --all-files"

[pypi-dependencies]
multihead = { path = ".", editable = true }
